### ISSUE TITLE
Could you please add sender name suffix?

### ISSUE THREAD

**Issue by emirefek** [PanCakeConnaisseur/auto_mail_accounts#10]
As I said. Could you please add sender name suffix?

**Comment by alexeyabel** [comment]
Why? What is the use case?

**Comment by emirefek** [comment]
for example "John | XYZ Corp."

**Comment by alexeyabel** [comment]
I am not currently planning to develop or maintain this app further. See message at the top of README.md for the reasons. You are of course free to fork and modify this app in accordance with it's open source license.
