### ISSUE TITLE
Can not be used with OAuth2 authentication

### ISSUE THREAD

**Issue by urp** [PanCakeConnaisseur/auto_mail_accounts#11]
Thank you for this useful piece of software.
I use Nextcloud in conjunction with a mailcow setup providing authentication via OAuth2.

# Problem
* Unfortunately, when using external authentication nextcloud seems to prefix usernames with the authenticator name
* Mailcow mailbox user user@domain.tld becomes Mailcow-user@domain.tld
* auto_mail_accounts is unable to get the correct email address

# Possible Solutions
* Autoremove Oauth2-prefix from username
* Use regex (replacements) to allow admins to extract/reconstruct the email address

**Comment by dgiebert** [comment]
Just adding to this issue: Using Social Login with Google results in an internal server error

**Comment by alexeyabel** [comment]
I am sorry but I am currently not planning to develop or maintain this app further. I had started migrating this app to the new log and event API but then realized that the Mail app now does everything that I need. See message at the top of the README.md for details. You are of course free to fork and modify this app in accordance with it's open source license.
