### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sunjam** [PanCakeConnaisseur/auto_mail_accounts#13]
Related to #12, please add support for PHP 8.  Support for it begins in 21, but 7.x will continue to be supported for the time being.

**Comment by alexeyabel** [comment]
I am sorry but I am currently not planning to develop or maintain this app further. I had started migrating this app to the new log and event API but then realized that the Mail app now does everything that I need. See message at the top of the README.md for details. You are of course free to fork and modify this app in accordance with it's open source license.
