### ISSUE TITLE
Error: Exception: Argument 3 passed ... must be of the type string, object given at <<closure>>

### ISSUE THREAD

**Issue by mistergibson** [PanCakeConnaisseur/auto_mail_accounts#14]
[index] Error: Exception: Argument 3 passed to OCA\AutoMailAccounts\Hooks\UserHooks::OCA\AutoMailAccounts\Hooks\{closure}() must be of the type string, object given at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\LoginController {}, "tryLogin")
1. /var/www/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OC\\Core\\Controller\\LoginController", "tryLogin", OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
2. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/login")
3. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /cloud/index.php/login
from 127.0.0.1 by g.gibson at 2021-03-22T11:20:04+00:00

**Comment by alexeyabel** [comment]
I am sorry but I am currently not planning to develop or maintain this app further. See message at the top of the README.md for details. You are of course free to fork and modify this app in accordance with it's open source license.
