### ISSUE TITLE
user deletion not possible if there is no mail account configured

### ISSUE THREAD

**Issue by mdik** [PanCakeConnaisseur/auto_mail_accounts#2]
If there are no mail accounts configured for a user, the deletion of that user fails when auto_mail_accounts is enabled.

This happens in the functions `getMailAccount()` respectively `getUsersFirstMailAccount()` which assume that there _is_ a mail account.

**Comment by mdik** [comment]
PS: Because I'm riding in with issues and pull requests: This app is seriously awesome and exactly what I need, and I am so, so happy that you wrote it, @PanCakeConnaisseur !!!

:heart: :heart: :heart:

**Comment by alexeyabel** [comment]
Thank you very much for the positive feedback. I will look into the issue.

**Comment by mdik** [comment]
Thank you!

**Comment by alexeyabel** [comment]
Fixed by 61e3c854e68aac27ede70d45c4f021c93499e5b1
