### ISSUE TITLE
Autologin in external sites

### ISSUE THREAD

**Issue by DeAlexPesh** [PanCakeConnaisseur/auto_mail_accounts#5]
Hi, 
Can you make analog for app [external sites](https://apps.nextcloud.com/apps/external)?
for example in rainloop sso on [this](https://github.com/pierre-alain-b/rainloop-nextcloud/issues/73#issuecomment-421346855)

**Comment by alexeyabel** [comment]
@DeAlexPesh Can you please elaborate on what exactly this app should be able to do?

**Comment by alexeyabel** [comment]
Closing due to lack of information provided.
