### ISSUE TITLE
when enabled, 500 error when adding an image to profile

### ISSUE THREAD

**Issue by sitedart-studio** [PanCakeConnaisseur/auto_mail_accounts#6]
When adding an image to a users profile, nextcloud throws a 500 error.. When Auto Mail is disabled images can be added normally,

Failed to load resource: the server responded with a status of 500 () in Chrome
 [02/Nov/2018:13:54:00 -0400] "POST /index.php/avatar/cropped HTTP/2.0" 500

POST","url":"\/avatar\/cropped","message":{"Exception":"Error","Message":"Call to a member function getMailAccount() on null""Code":0,"Trace":[{"file":"\/home\/franklinnc\/cloud.franklinnc.com\/apps\/auto_mail_accounts\/lib\/Hooks\/UserHooks.php","line":146,"function":"getUsersFirstMailAccount","class":"OCA\\AutoMailAccounts\\Hooks\\UserHooks","type":"->","args":["*** sensitive parameter replaced ***"]},{"function":"OCA\\AutoMailAccounts\\Hooks\\{closure}","class":"OCA\\AutoMailAccounts\\Hooks\\UserHooks","type":"->","args":["*** sensitive parameters replaced ***"]}

**Comment by alexeyabel** [comment]
Should be fixed by 61e3c854e68aac27ede70d45c4f021c93499e5b1.
