### ISSUE TITLE
Support for NC 16/17

### ISSUE THREAD

**Issue by grickard** [PanCakeConnaisseur/auto_mail_accounts#8]
Hello,

I have an external IMAP/SMTP server and this would be the perfect solution for me. Are there any plans for future support with NC 16 or 17?

I currently need a way to update the mailbox password on the imap server when a user does a password reset in NC.

Thanks!

**Comment by alexeyabel** [comment]
Support for Nextcloud 16, 17 and 18 has just been added in the 0.1.4 release.
